# Generated by Django 5.1.5 on 2025-01-23 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('startup_starting_date', models.DateField(blank=True, null=True)),
                ('startup_profile_visit_count', models.PositiveIntegerField(default=0)),
                ('startup_user', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to='authenticator.startupuser')),
            ],
        ),
        migrations.CreateModel(
            name='StartupVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'like'), (0, 'nothing')])),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.startupprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'startup_profile')},
            },
        ),
    ]
