# Generated by Django 5.1.3 on 2024-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='email',
            field=models.EmailField(default='example@example.com', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='first_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='last_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='socials',
            field=models.JSONField(default=dict),
        ),
    ]
