# Generated by Django 5.1.3 on 2024-11-06 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_baseuser_email_alter_investoruser_categories_and_more'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupprofile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='page',
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='required_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='startup_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.startupuser'),
        ),
    ]
