# Generated by Django 5.1.4 on 2025-01-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_baseprofile_base_user_alter_baseuser_user_type_and_more'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='startup_user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to='authenticator.startupuser'),
        ),
    ]
