# Generated by Django 5.1.3 on 2024-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_alter_startupprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
