# Generated by Django 5.1.3 on 2024-11-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_rename_description_startupposition_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupposition',
            old_name='bio',
            new_name='description',
        ),
    ]
