# Generated by Django 5.1.3 on 2024-11-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_rename_bio_startupposition_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupposition',
            old_name='description',
            new_name='bio',
        ),
    ]
