# Generated by Django 5.1.3 on 2024-11-21 22:05

import authenticator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_remove_startupprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='email',
            field=models.EmailField(default='example@example.com', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='first_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='header_picture',
            field=models.ImageField(blank=True, default='header_pics/default_header.jpg', null=True, upload_to=authenticator.models.user_header_picture_path),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='last_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to=authenticator.models.user_profile_picture_path),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='socials',
            field=models.JSONField(default=dict),
        ),
    ]
