# Generated by Django 5.1.3 on 2024-11-21 22:24

import startup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_startupprofile_bio_startupprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='email',
            field=models.EmailField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='header_picture',
            field=models.ImageField(blank=True, default='header_pics/default_header.jpg', null=True, upload_to=startup.models.user_header_picture_path),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to=startup.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='socials',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
