# Generated by Django 5.1.3 on 2024-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_alter_startupprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='email',
            field=models.EmailField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
