# Generated by Django 5.1.3 on 2024-11-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_remove_baseuser_about_me_remove_baseuser_name_and_more'),
        ('startup', '0009_alter_startupprofile_email_alter_startupprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='page',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='startup_user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authenticator.startupuser'),
        ),
    ]
