# Generated by Django 5.1.2 on 2024-11-05 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('total', models.IntegerField()),
                ('funded', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('available', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.investoruser')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.investoruser')),
                ('startup_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bombfunding.startupposition')),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('page', models.JSONField()),
                ('startup_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticator.startupuser')),
            ],
        ),
        migrations.AddField(
            model_name='startupposition',
            name='startup_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bombfunding.startupprofile'),
        ),
        migrations.CreateModel(
            name='StartupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bombfunding.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StartupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bombfunding.investposition')),
                ('startup_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bombfunding.startupprofile')),
            ],
        ),
    ]
