# Generated by Django 5.1.3 on 2024-11-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bombfunding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupcomment',
            name='startup_profile',
        ),
        migrations.RemoveField(
            model_name='startupcomment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='startupposition',
            name='startup_profile',
        ),
        migrations.RemoveField(
            model_name='investorapplication',
            name='startup_position',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='startup_user',
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='investor_position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bombfunding.investposition'),
        ),
        migrations.AddField(
            model_name='investposition',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='StartupApplication',
        ),
        migrations.DeleteModel(
            name='StartupComment',
        ),
        migrations.DeleteModel(
            name='StartupPosition',
        ),
        migrations.DeleteModel(
            name='StartupProfile',
        ),
    ]
