# Generated by Django 5.1.2 on 2024-10-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bombfunding', '0002_alter_startupcomment_username_and_more'),
        ('authenticator', '0003_remove_baseuser_groups_remove_baseuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authenticator.baseuser'),
        ),
        migrations.AlterField(
            model_name='investoruser',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authenticator.baseuser'),
        ),
        migrations.AlterField(
            model_name='startupcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.baseuser'),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authenticator.baseuser'),
        ),
    ]
