# Generated by Django 5.1.4 on 2025-01-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0002_alter_startupprofile_startup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profilepage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.startupprofile')),
            ],
        ),
    ]
