from django.urls import path
from .views import (
    ProjectStatisticsLast6MonthsView,
    ProjectStatisticsLast7DaysView,
    ProjectVisitView,
    ProjectVisitCountView,
    StartupVisitCountView,
    StartupStatisticsLast30DaysView,
    StartupStatisticsLast90DaysView,
    StartupStatisticsLastYearView,  
    ProjectStatisticsLast30DaysView, 
    ProjectStatisticsLast90DaysView,
    ProjectStatisticsLastYearView,  
    StartupFundStatisticsLast30DaysView,
    StartupFundStatisticsLast90DaysView, 
    StartupFundStatisticsLastYearView, 
    ProjectFundStatisticsLast30DaysView, 
    ProjectFundStatisticsLast90DaysView, 
    ProjectFundStatisticsLastYearView,  
)

urlpatterns = [
    # path('last-7-days/', ProjectStatisticsLast7DaysView.as_view(), name='profile-statistics-last-7-days'),
    # path('last-6-months/', ProjectStatisticsLast6MonthsView.as_view(), name='profile-statistics-last-6-months'),
    path('visit/<int:project_id>/', ProjectVisitView.as_view(), name='project-visit'),
    path('visit/project/<int:project_id>/', ProjectVisitCountView.as_view(), name='project-visit-count'),
    path('visit/startup/<int:startup_id>/', StartupVisitCountView.as_view(), name='startup-visit-count'),
    path('last-30-days/', StartupStatisticsLast30DaysView.as_view(), name='startup-statistics-last-30-days'),
    path('last-90-days/', StartupStatisticsLast90DaysView.as_view(), name='startup-statistics-last-90-days'),
    path('last-year/', StartupStatisticsLastYearView.as_view(), name='startup-statistics-last-year'),
    path('project/<int:project_id>/last-30-days/', ProjectStatisticsLast30DaysView.as_view(), name='project-statistics-last-30-days'), 
    path('project/<int:project_id>/last-90-days/', ProjectStatisticsLast90DaysView.as_view(), name='project-statistics-last-90-days'),
    path('project/<int:project_id>/last-year/', ProjectStatisticsLastYearView.as_view(), name='project-statistics-last-year'),
    path('fund/last-30-days/', StartupFundStatisticsLast30DaysView.as_view(), name='startup-fund-statistics-last-30-days'), 
    path('fund/last-90-days/', StartupFundStatisticsLast90DaysView.as_view(), name='startup-fund-statistics-last-90-days'), 
    path('fund/last-year/', StartupFundStatisticsLastYearView.as_view(), name='startup-fund-statistics-last-year'),        
    path('project/<int:project_id>/fund/last-30-days/', ProjectFundStatisticsLast30DaysView.as_view(), name='project-fund-statistics-last-30-days'), 
    path('project/<int:project_id>/fund/last-90-days/', ProjectFundStatisticsLast90DaysView.as_view(), name='project-fund-statistics-last-90-days'),
    path('project/<int:project_id>/fund/last-year/', ProjectFundStatisticsLastYearView.as_view(), name='project-fund-statistics-last-year'),     
]
