# Generated by Django 5.1.2 on 2024-11-02 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=' ', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('about_me', models.TextField(default=' ')),
                ('user_type', models.CharField(choices=[('investor', 'Investor'), ('startup', 'Startup'), ('basic', 'Basic')], default='basic', max_length=10)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must be at least 8 characters long, contain an uppercase letter, a lowercase letter, a number, and a special character.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorUser',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('page', models.JSONField()),
                ('categories', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StartupUser',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
