# Generated by Django 5.1.2 on 2024-10-30 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('about_me', models.TextField()),
                ('user_type', models.CharField(choices=[('Investor', 'Investor'), ('Startup', 'Startup'), ('Basic', 'Basic')], default='Basic', max_length=10)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long, contain an uppercase letter, a lowercase letter, a number, and a special character.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')])),
            ],
        ),
    ]
