# Generated by Django 5.1.4 on 2025-01-02 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='base_user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('basic', 'Basic')], default='basic', max_length=10),
        ),
        migrations.DeleteModel(
            name='InvestorUser',
        ),
    ]
