# Generated by Django 5.1.3 on 2024-11-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basicuserprofile',
            name='about_me',
        ),
    ]
