# Generated by Django 5.1.3 on 2024-11-21 21:29

import authenticator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@example.com', editable=False, max_length=100)),
                ('first_name', models.CharField(editable=False, max_length=50, null=True)),
                ('last_name', models.CharField(editable=False, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('socials', models.JSONField(default=dict)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=authenticator.models.user_profile_picture_path)),
                ('header_picture', models.ImageField(blank=True, null=True, upload_to=authenticator.models.user_header_picture_path)),
                ('interests', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='BasicUserProfile',
        ),
    ]
