# Generated by Django 5.1.2 on 2024-10-30 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_baseuser_groups_baseuser_is_active_baseuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long, contain an uppercase letter, a lowercase letter, a number, and a special character.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('Investor', 'Investor'), ('Startup', 'Startup'), ('Basic', 'Basic')], default='Basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
