# Generated by Django 5.1.3 on 2024-11-14 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_baseuser_is_confirmed_baseuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, default=' ')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('interests', models.CharField(blank=True, max_length=500)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
