# Generated by Django 5.1.3 on 2024-11-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_baseuser_is_staff_baseuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_superuser',
        ),
    ]
