# Generated by Django 5.1.3 on 2024-11-14 13:46

import authenticator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_basicuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=authenticator.models.user_profile_picture_path),
        ),
    ]
