# Generated by Django 5.1.2 on 2024-11-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_baseuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='is_active',
            new_name='is_confirmed',
        ),
    ]
