# Generated by Django 5.1.3 on 2024-11-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_basicuserprofile_delete_baseuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basicuserprofile',
            name='about_me',
        ),
    ]
