# Generated by Django 5.1.2 on 2024-10-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_remove_baseuser_groups_remove_baseuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
