# Generated by Django 5.1.2 on 2024-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_rename_is_active_baseuser_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoruser',
            name='page',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
