# Generated by Django 5.1.3 on 2024-11-14 14:33

import authenticator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_alter_basicuserprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='header_picture',
            field=models.ImageField(blank=True, null=True, upload_to=authenticator.models.user_header_picture_path),
        ),
    ]
