# Generated by Django 5.1.2 on 2024-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_remove_baseuser_about_me_remove_baseuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
