# Generated by Django 5.1.3 on 2024-11-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_baseuser_is_active_baseuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_active',
        ),
    ]
