# Generated by Django 5.1.2 on 2024-11-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_alter_investoruser_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoruser',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
