# Generated by Django 5.1.2 on 2024-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_remove_baseuser_groups_remove_baseuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
