# Generated by Django 5.1.4 on 2025-01-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.JSONField(blank=True, default=dict)),
                ('views', models.JSONField(blank=True, default=dict)),
                ('fund', models.JSONField(blank=True, default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='project.project')),
            ],
            options={
                'verbose_name': 'Project Statistic',
                'verbose_name_plural': 'Project Statistics',
            },
        ),
    ]
